version: '3'

services:
  php:
    container_name: php-laravel
    build: ./docker/php
    volumes:
    - ./server:/var/www

  nginx:
    image: nginx
    container_name: nginx-laravel
    ports:
    - 8010:80
    volumes:
    - ./server:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  db:
    image: mysql:5.7
    container_name: db-laravel
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: AppModernClub
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3310:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-laravel
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db-laravel
    links:
      - db
    ports:
      - 8011:80
    volumes:
      - /sessions
